# Settings for the app
app:
  # HTML Title
  title: "#SandyVolunteer"
  # Header name
  name: "#SandyVolunteer"
  # Meta description that will show up in Google search results
  meta_description: "Mapping information from #SandyVolunteer about volunteering opportunities and donation sites for Sandy cleanup."

# Settings for map and layer configs
map:
  options:
    center:
      lat: 40.684896
      lng: -73.9
    zoom: 11
    minZoom: 9
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/mapbox.mapbox-streets/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Donation dropoff:
    default: green_feature
    focused: green_focused
  Volunteering for cleanup:
    default: yellow_feature
    focused: yellow_focused
  Volunteering for shelter help:
    default: red_feature
    focused: red_focused

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  yellow_feature:
    iconUrl: /static/css/images/feature-point-yellow.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red_feature:
    iconUrl: /static/css/images/feature-point-red.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  green_feature:
    iconUrl: /static/css/images/feature-point-green.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  yellow_focused:
    iconUrl: /static/css/images/marker-focused-yellow.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  red_focused:
    iconUrl: /static/css/images/marker-focused-red.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  green_focused:
    iconUrl: /static/css/images/marker-focused-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

place:
  adding_supported: true
  title: Details
  add_button_label: Add a location
  action_text: identified
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: What?
      type: text
      name: name
      attrs:
        - key: placeholder
          value: "what"
        - key: size
          value: 30
    - prompt: Where?
      type: textarea
      name: address
      attrs:
        - key: placeholder
          value: "Location/street"
    - prompt: Zip
      type: text
      name: zip
      attrs:
        - key: placeholder
          value: "5 digit zip"
    - prompt: Borough or Municipality
      type: text
      name: borough
      attrs:
        - key: placeholder
          value: "Borough or Muni"
    - prompt: "EITHER -- When in general?"
      type: textarea
      name: when
      attrs:
        - key: placeholder
          value: "e.g. every day from 10am until it gets dark"
    - prompt: "OR --- specifics.... When on Saturday?"
      type: text
      name: when-sat
      attrs:
        - key: placeholder
          value: "e.g. 10am-5pm"
    - prompt: ...when on Sunday?
      type: text
      name: when-sun
    - prompt: ...when on Monday?
      type: text
      name: when-mon
    - prompt: ...when after Monday?
      type: text
      name: when-beyond
    - prompt: Activity type
      type: select
      options:
        - Donation dropoff
        - Volunteering for cleanup
        - Volunteering for shelter help 
      name: location_type
    - prompt: "Source/more info"
      type: text
      name: info_url
      optional: true
      attrs:
        - key: placeholder
          value: url
        - key: size
          value: 30
    - prompt: Contact info
      type: textarea
      name: contact_info
      attrs:
        - key: placeholder
          value: "Who to contact for more info"
    - prompt: Details
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: "Explain what's going on"
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Add comments or corrections
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: supported
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/about.html
    start_page: true
  - title: Data
    slug: data
    url: /static/pages/data.html
  - title: Filter location types
    pages:
      - title: All
        external: true
        url: /

      - title: Donation dropoff
        external: true
        url: /donation dropoff
      
      - title: Volunteering for cleanup
        external: true
        url: /volunteering for cleanup

      - title: Volunteering for shelter help
        external: true
        url: /volunteering for shelter help
